// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hddvowihnkfjbopbtwbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkZHZvd2lobmtmamJvcGJ0d2J1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMDAwNzUsImV4cCI6MjA2MDg3NjA3NX0.TsCqg4aJ6wS97KMUn5Ao-J8Z49S1nHwDM0l5gMM1Vj8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);